# Generated by Django 5.1.2 on 2024-11-04 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0001_initial'),
        ('source', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('serialNumber', models.CharField(max_length=150)),
                ('anomaly', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('observation', models.CharField(max_length=150)),
                ('date_entree', models.DateField(max_length=100)),
                ('date_sortie', models.DateField(max_length=100)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locality.locality')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source.source')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
