# Generated by Django 4.2.14 on 2024-11-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0001_initial'),
        ('source', '0001_initial'),
        ('maintenance', '0002_alter_maintenance_anomaly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locality.locality'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source.source'),
        ),
    ]
