# Generated by Django 4.2.14 on 2024-11-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
        ('locality', '0001_initial'),
        ('maintenance', '0003_alter_maintenance_locality_alter_maintenance_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locality.locality'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='source.source'),
        ),
    ]
