# Generated by Django 4.2.14 on 2024-11-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_maintenance_anomaly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='anomaly',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='observation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='ticket',
            field=models.CharField(max_length=100),
        ),
    ]
