# Generated by Django 4.2.16 on 2024-11-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0002_alter_hotline_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotline',
            name='status',
        ),
    ]
