# Generated by Django 4.2.16 on 2024-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0003_remove_hotline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='isMaintenance',
            field=models.CharField(max_length=10),
        ),
    ]
