# Generated by Django 4.2.16 on 2024-11-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0004_alter_hotline_ismaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='updated_by',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
