# Generated by Django 4.2.16 on 2024-11-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0005_alter_hotline_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
