# Generated by Django 4.2.16 on 2024-11-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0006_alter_hotline_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='updated_by',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
